version: '3'  
services:  
 web:  
  build: .  
  command: 
   bash -c 'rails db:create && rails db:migrate && bundle exec rails server -p 3000 -b 0.0.0.0'  
  ports:  
   - 80:3000  
  volumes:  
   - .:/app  
  depends_on:  
   - db  
  tty: true  
  stdin_open: true  
 db:  
  image: mysql:5.7  
  volumes:  
   - db-volume:/var/lib/mysql  
  environment:  
    MYSQL_ROOT_PASSWORD: password 
volumes:  
 db-volume:
